[book]
title = "通过例子学 Rust 中文版"
description = "通过例子学 Rust, Rust By Example 中文版，RBE 中文版，本书通过详细的可运行的 Rust 程序来讲解 Rust 语言有关的知识点，通俗易懂，是 Rust 初学者必备的学习参考书，同时也能作为 Rust 工程师日常工作中快速查找知识点的必备查询手册。"
author = "Steve Klabnik and Carol Nichols, with Contributions from the Rust Community"
translator = "Aaran Xu"
language = "zh-CN"

[output.html]
additional-js = ["language.js"]
git-repository-url = "https://github.com/rust-lang-cn/rust-by-example-cn"
edit-url-template = "https://github.com/rust-lang-cn/rust-by-example-cn/edit/master/{path}"

[output.html.playpen]
editable = true
editor = "ace"

[output.html.fold]
# 将书籍导航展开，作为书籍目录，收缩起来不便于章节快速查找 —— 2022-01-26
enable = false

[rust]
edition = "2021"